name: Create Branch Version

on:
  push:
    branches:
      - atoms

jobs:
  create-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set branch name
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        run: echo "::set-env name=BRANCH_NAME::$(git rev-parse --abbrev-ref HEAD)"

      - name: Check if the branch is the target branch
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        run: |
          if [ "${{ env.BRANCH_NAME }}" != "atoms" ]; then
            echo "This workflow is only for the 'atoms' branch. Exiting..."
            exit 1
          fi

      - name: Create and checkout new branch
        run: |
          # Determine the latest version tag
          latest_tag=$(git tag -l --sort=-v:refname | head -n 1)

          # If there are no tags yet, start with version 0.0.1
          if [ -z "$latest_tag" ]; then
            new_version="v0.0.1"
          else
            # Increment the PATCH version for subsequent pushes
            IFS='.' read -ra version_parts <<< "$latest_tag"
            new_patch=$((version_parts[2] + 1))
            new_version="${version_parts[0]}.${version_parts[1]}.$new_patch"
          fi

          # Create a new branch with the version name
          git checkout -b "atoms-$new_version"
          git push origin "atoms-$new_version"

# Add more steps if needed for your specific requirements
